// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_editor.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cloneAppAsShadowDraft = `-- name: CloneAppAsShadowDraft :one
INSERT INTO apps (
    id, name, slug, description, organization_id, visibility_status, health_status, 
    verification_status, ranking_weight, icon_key, metadata, source_app_id, version, updated_by
)
SELECT 
    $1, name, slug, description, organization_id, 'draft', health_status,
    verification_status, ranking_weight, icon_key, metadata, $2, 1, $3
FROM apps WHERE id = $2
RETURNING id, slug, name, description, organization_id, visibility_status, health_status, verification_status, ranking_weight, icon_key, metadata, version, created_at, updated_at, deleted_at, source, source_app_id, updated_by
`

type CloneAppAsShadowDraftParams struct {
	ID          uuid.UUID   `json:"id"`
	SourceAppID pgtype.UUID `json:"source_app_id"`
	UpdatedBy   pgtype.UUID `json:"updated_by"`
}

func (q *Queries) CloneAppAsShadowDraft(ctx context.Context, arg CloneAppAsShadowDraftParams) (App, error) {
	row := q.db.QueryRow(ctx, cloneAppAsShadowDraft, arg.ID, arg.SourceAppID, arg.UpdatedBy)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OrganizationID,
		&i.VisibilityStatus,
		&i.HealthStatus,
		&i.VerificationStatus,
		&i.RankingWeight,
		&i.IconKey,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Source,
		&i.SourceAppID,
		&i.UpdatedBy,
	)
	return i, err
}

const patchApp = `-- name: PatchApp :one
UPDATE apps SET
    name = $2,
    description = $3,
    organization_id = $4,
    health_status = $5,
    ranking_weight = $6,
    icon_key = $7,
    version = version + 1,
    updated_at = NOW(),
    updated_by = $8
WHERE id = $1 AND version = $9
RETURNING id, slug, name, description, organization_id, visibility_status, health_status, verification_status, ranking_weight, icon_key, metadata, version, created_at, updated_at, deleted_at, source, source_app_id, updated_by
`

type PatchAppParams struct {
	ID             uuid.UUID    `json:"id"`
	Name           string       `json:"name"`
	Description    string       `json:"description"`
	OrganizationID uuid.UUID    `json:"organization_id"`
	HealthStatus   HealthStatus `json:"health_status"`
	RankingWeight  int32        `json:"ranking_weight"`
	IconKey        string       `json:"icon_key"`
	UpdatedBy      pgtype.UUID  `json:"updated_by"`
	Version        int64        `json:"version"`
}

func (q *Queries) PatchApp(ctx context.Context, arg PatchAppParams) (App, error) {
	row := q.db.QueryRow(ctx, patchApp,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OrganizationID,
		arg.HealthStatus,
		arg.RankingWeight,
		arg.IconKey,
		arg.UpdatedBy,
		arg.Version,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OrganizationID,
		&i.VisibilityStatus,
		&i.HealthStatus,
		&i.VerificationStatus,
		&i.RankingWeight,
		&i.IconKey,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Source,
		&i.SourceAppID,
		&i.UpdatedBy,
	)
	return i, err
}
