// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveShadowDrafts = `-- name: ArchiveShadowDrafts :exec
UPDATE apps SET visibility_status = 'archived'
WHERE source_app_id = $1 AND visibility_status != 'archived'
`

func (q *Queries) ArchiveShadowDrafts(ctx context.Context, sourceAppID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveShadowDrafts, sourceAppID)
	return err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (id, event_type, payload, status)
VALUES ($1, $2, $3, 'pending')
`

type CreateOutboxEventParams struct {
	ID        uuid.UUID `json:"id"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent, arg.ID, arg.EventType, arg.Payload)
	return err
}

const getAdminDashboardStats = `-- name: GetAdminDashboardStats :one
SELECT 
    COUNT(*) FILTER (WHERE visibility_status = 'review') AS pending_reviews,
    COUNT(*) FILTER (WHERE visibility_status = 'needs_changes') AS needs_changes,
    COUNT(*) FILTER (WHERE visibility_status = 'published' AND created_at >= NOW() - INTERVAL '24 HOURS') AS published_today
FROM apps
`

type GetAdminDashboardStatsRow struct {
	PendingReviews int64 `json:"pending_reviews"`
	NeedsChanges   int64 `json:"needs_changes"`
	PublishedToday int64 `json:"published_today"`
}

func (q *Queries) GetAdminDashboardStats(ctx context.Context) (GetAdminDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminDashboardStats)
	var i GetAdminDashboardStatsRow
	err := row.Scan(&i.PendingReviews, &i.NeedsChanges, &i.PublishedToday)
	return i, err
}

const getReviewQueue = `-- name: GetReviewQueue :many
SELECT id, slug, name, description, organization_id, visibility_status, health_status, verification_status, ranking_weight, icon_key, metadata, version, created_at, updated_at, deleted_at, source, source_app_id, updated_by FROM apps
WHERE visibility_status IN ('draft', 'review', 'needs_changes')
ORDER BY 
    CASE visibility_status
        WHEN 'review' THEN 1
        WHEN 'draft' THEN 2
        WHEN 'needs_changes' THEN 3
        ELSE 4
    END ASC,
    created_at ASC
`

func (q *Queries) GetReviewQueue(ctx context.Context) ([]App, error) {
	rows, err := q.db.Query(ctx, getReviewQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []App
	for rows.Next() {
		var i App
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.OrganizationID,
			&i.VisibilityStatus,
			&i.HealthStatus,
			&i.VerificationStatus,
			&i.RankingWeight,
			&i.IconKey,
			&i.Metadata,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Source,
			&i.SourceAppID,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppStatus = `-- name: UpdateAppStatus :one
UPDATE apps SET 
    visibility_status = $2,
    updated_at = NOW(),
    updated_by = $3
WHERE id = $1
RETURNING id, slug, name, description, organization_id, visibility_status, health_status, verification_status, ranking_weight, icon_key, metadata, version, created_at, updated_at, deleted_at, source, source_app_id, updated_by
`

type UpdateAppStatusParams struct {
	ID               uuid.UUID        `json:"id"`
	VisibilityStatus VisibilityStatus `json:"visibility_status"`
	UpdatedBy        pgtype.UUID      `json:"updated_by"`
}

func (q *Queries) UpdateAppStatus(ctx context.Context, arg UpdateAppStatusParams) (App, error) {
	row := q.db.QueryRow(ctx, updateAppStatus, arg.ID, arg.VisibilityStatus, arg.UpdatedBy)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OrganizationID,
		&i.VisibilityStatus,
		&i.HealthStatus,
		&i.VerificationStatus,
		&i.RankingWeight,
		&i.IconKey,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Source,
		&i.SourceAppID,
		&i.UpdatedBy,
	)
	return i, err
}
