// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apps.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createApp = `-- name: CreateApp :one
INSERT INTO apps (
    id, slug, name, description, organization_id, 
    visibility_status, health_status, verification_status,
    ranking_weight, icon_key, metadata, version, source
) VALUES (
    $1, $2, $3, $4, $5, 
    $6, $7, $8, 
    $9, $10, $11, $12, $13
) RETURNING id, slug, name, description, organization_id, visibility_status, health_status, verification_status, ranking_weight, icon_key, metadata, version, created_at, updated_at, deleted_at, source, source_app_id, updated_by
`

type CreateAppParams struct {
	ID                 uuid.UUID          `json:"id"`
	Slug               string             `json:"slug"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	VisibilityStatus   VisibilityStatus   `json:"visibility_status"`
	HealthStatus       HealthStatus       `json:"health_status"`
	VerificationStatus VerificationStatus `json:"verification_status"`
	RankingWeight      int32              `json:"ranking_weight"`
	IconKey            string             `json:"icon_key"`
	Metadata           []byte             `json:"metadata"`
	Version            int64              `json:"version"`
	Source             string             `json:"source"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.OrganizationID,
		arg.VisibilityStatus,
		arg.HealthStatus,
		arg.VerificationStatus,
		arg.RankingWeight,
		arg.IconKey,
		arg.Metadata,
		arg.Version,
		arg.Source,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OrganizationID,
		&i.VisibilityStatus,
		&i.HealthStatus,
		&i.VerificationStatus,
		&i.RankingWeight,
		&i.IconKey,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Source,
		&i.SourceAppID,
		&i.UpdatedBy,
	)
	return i, err
}

const getApp = `-- name: GetApp :one
SELECT id, slug, name, description, organization_id, visibility_status, health_status, verification_status, ranking_weight, icon_key, metadata, version, created_at, updated_at, deleted_at, source, source_app_id, updated_by FROM apps WHERE id = $1 LIMIT 1
`

func (q *Queries) GetApp(ctx context.Context, id uuid.UUID) (App, error) {
	row := q.db.QueryRow(ctx, getApp, id)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OrganizationID,
		&i.VisibilityStatus,
		&i.HealthStatus,
		&i.VerificationStatus,
		&i.RankingWeight,
		&i.IconKey,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Source,
		&i.SourceAppID,
		&i.UpdatedBy,
	)
	return i, err
}

const getAppBySlug = `-- name: GetAppBySlug :one
SELECT id, slug, name, description, organization_id, visibility_status, health_status, verification_status, ranking_weight, icon_key, metadata, version, created_at, updated_at, deleted_at, source, source_app_id, updated_by FROM apps WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetAppBySlug(ctx context.Context, slug string) (App, error) {
	row := q.db.QueryRow(ctx, getAppBySlug, slug)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OrganizationID,
		&i.VisibilityStatus,
		&i.HealthStatus,
		&i.VerificationStatus,
		&i.RankingWeight,
		&i.IconKey,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Source,
		&i.SourceAppID,
		&i.UpdatedBy,
	)
	return i, err
}

const updateApp = `-- name: UpdateApp :one
UPDATE apps SET
    name = $2,
    description = $3,
    organization_id = $4,
    visibility_status = $5,
    health_status = $6,
    verification_status = $7,
    ranking_weight = $8,
    icon_key = $9,
    metadata = $10,
    version = version + 1,
    source = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, slug, name, description, organization_id, visibility_status, health_status, verification_status, ranking_weight, icon_key, metadata, version, created_at, updated_at, deleted_at, source, source_app_id, updated_by
`

type UpdateAppParams struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	VisibilityStatus   VisibilityStatus   `json:"visibility_status"`
	HealthStatus       HealthStatus       `json:"health_status"`
	VerificationStatus VerificationStatus `json:"verification_status"`
	RankingWeight      int32              `json:"ranking_weight"`
	IconKey            string             `json:"icon_key"`
	Metadata           []byte             `json:"metadata"`
	Source             string             `json:"source"`
}

func (q *Queries) UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, updateApp,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OrganizationID,
		arg.VisibilityStatus,
		arg.HealthStatus,
		arg.VerificationStatus,
		arg.RankingWeight,
		arg.IconKey,
		arg.Metadata,
		arg.Source,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.OrganizationID,
		&i.VisibilityStatus,
		&i.HealthStatus,
		&i.VerificationStatus,
		&i.RankingWeight,
		&i.IconKey,
		&i.Metadata,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Source,
		&i.SourceAppID,
		&i.UpdatedBy,
	)
	return i, err
}
