// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editor.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAppAlias = `-- name: CreateAppAlias :exec
INSERT INTO aliases (id, app_id, alias) VALUES ($1, $2, $3)
`

type CreateAppAliasParams struct {
	ID    uuid.UUID `json:"id"`
	AppID uuid.UUID `json:"app_id"`
	Alias string    `json:"alias"`
}

func (q *Queries) CreateAppAlias(ctx context.Context, arg CreateAppAliasParams) error {
	_, err := q.db.Exec(ctx, createAppAlias, arg.ID, arg.AppID, arg.Alias)
	return err
}

const createAppCategory = `-- name: CreateAppCategory :exec
INSERT INTO app_categories (app_id, category_id) VALUES ($1, $2)
`

type CreateAppCategoryParams struct {
	AppID      uuid.UUID `json:"app_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) CreateAppCategory(ctx context.Context, arg CreateAppCategoryParams) error {
	_, err := q.db.Exec(ctx, createAppCategory, arg.AppID, arg.CategoryID)
	return err
}

const createAppLink = `-- name: CreateAppLink :exec
INSERT INTO app_links (id, app_id, link_type, url) VALUES ($1, $2, $3, $4)
`

type CreateAppLinkParams struct {
	ID       uuid.UUID `json:"id"`
	AppID    uuid.UUID `json:"app_id"`
	LinkType string    `json:"link_type"`
	Url      string    `json:"url"`
}

func (q *Queries) CreateAppLink(ctx context.Context, arg CreateAppLinkParams) error {
	_, err := q.db.Exec(ctx, createAppLink,
		arg.ID,
		arg.AppID,
		arg.LinkType,
		arg.Url,
	)
	return err
}

const createAppMedia = `-- name: CreateAppMedia :exec
INSERT INTO media (id, app_id, media_key, media_type, order_index) VALUES ($1, $2, $3, $4, $5)
`

type CreateAppMediaParams struct {
	ID         uuid.UUID `json:"id"`
	AppID      uuid.UUID `json:"app_id"`
	MediaKey   string    `json:"media_key"`
	MediaType  string    `json:"media_type"`
	OrderIndex int32     `json:"order_index"`
}

func (q *Queries) CreateAppMedia(ctx context.Context, arg CreateAppMediaParams) error {
	_, err := q.db.Exec(ctx, createAppMedia,
		arg.ID,
		arg.AppID,
		arg.MediaKey,
		arg.MediaType,
		arg.OrderIndex,
	)
	return err
}

const createAppPlatform = `-- name: CreateAppPlatform :exec
INSERT INTO app_platforms (app_id, platform_id) VALUES ($1, $2)
`

type CreateAppPlatformParams struct {
	AppID      uuid.UUID `json:"app_id"`
	PlatformID uuid.UUID `json:"platform_id"`
}

func (q *Queries) CreateAppPlatform(ctx context.Context, arg CreateAppPlatformParams) error {
	_, err := q.db.Exec(ctx, createAppPlatform, arg.AppID, arg.PlatformID)
	return err
}

const createAppPricing = `-- name: CreateAppPricing :exec
INSERT INTO app_pricing (app_id, pricing_id) VALUES ($1, $2)
`

type CreateAppPricingParams struct {
	AppID     uuid.UUID `json:"app_id"`
	PricingID uuid.UUID `json:"pricing_id"`
}

func (q *Queries) CreateAppPricing(ctx context.Context, arg CreateAppPricingParams) error {
	_, err := q.db.Exec(ctx, createAppPricing, arg.AppID, arg.PricingID)
	return err
}

const deleteAppAliases = `-- name: DeleteAppAliases :exec
DELETE FROM aliases WHERE app_id = $1
`

func (q *Queries) DeleteAppAliases(ctx context.Context, appID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppAliases, appID)
	return err
}

const deleteAppCategories = `-- name: DeleteAppCategories :exec
DELETE FROM app_categories WHERE app_id = $1
`

func (q *Queries) DeleteAppCategories(ctx context.Context, appID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppCategories, appID)
	return err
}

const deleteAppLinks = `-- name: DeleteAppLinks :exec
DELETE FROM app_links WHERE app_id = $1
`

func (q *Queries) DeleteAppLinks(ctx context.Context, appID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppLinks, appID)
	return err
}

const deleteAppMedia = `-- name: DeleteAppMedia :exec
DELETE FROM media WHERE app_id = $1
`

func (q *Queries) DeleteAppMedia(ctx context.Context, appID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppMedia, appID)
	return err
}

const deleteAppPlatforms = `-- name: DeleteAppPlatforms :exec
DELETE FROM app_platforms WHERE app_id = $1
`

func (q *Queries) DeleteAppPlatforms(ctx context.Context, appID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppPlatforms, appID)
	return err
}

const deleteAppPricing = `-- name: DeleteAppPricing :exec
DELETE FROM app_pricing WHERE app_id = $1
`

func (q *Queries) DeleteAppPricing(ctx context.Context, appID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppPricing, appID)
	return err
}
