// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createImport = `-- name: CreateImport :one
INSERT INTO imports (
    id, source, status, started_at
) VALUES (
    $1, $2, $3, NOW()
) RETURNING id, started_at, finished_at, source, status, report
`

type CreateImportParams struct {
	ID     uuid.UUID `json:"id"`
	Source string    `json:"source"`
	Status string    `json:"status"`
}

func (q *Queries) CreateImport(ctx context.Context, arg CreateImportParams) (Import, error) {
	row := q.db.QueryRow(ctx, createImport, arg.ID, arg.Source, arg.Status)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Source,
		&i.Status,
		&i.Report,
	)
	return i, err
}

const updateImport = `-- name: UpdateImport :one
UPDATE imports SET
    status = $2,
    finished_at = NOW(),
    report = $3
WHERE id = $1
RETURNING id, started_at, finished_at, source, status, report
`

type UpdateImportParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Report []byte    `json:"report"`
}

func (q *Queries) UpdateImport(ctx context.Context, arg UpdateImportParams) (Import, error) {
	row := q.db.QueryRow(ctx, updateImport, arg.ID, arg.Status, arg.Report)
	var i Import
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Source,
		&i.Status,
		&i.Report,
	)
	return i, err
}
