// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type HealthStatus string

const (
	HealthStatusOperational HealthStatus = "operational"
	HealthStatusDegraded    HealthStatus = "degraded"
	HealthStatusMaintenance HealthStatus = "maintenance"
	HealthStatusOutage      HealthStatus = "outage"
	HealthStatusUnknown     HealthStatus = "unknown"
)

func (e *HealthStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HealthStatus(s)
	case string:
		*e = HealthStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HealthStatus: %T", src)
	}
	return nil
}

type NullHealthStatus struct {
	HealthStatus HealthStatus `json:"health_status"`
	Valid        bool         `json:"valid"` // Valid is true if HealthStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHealthStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HealthStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HealthStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHealthStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HealthStatus), nil
}

type UserRole string

const (
	UserRoleViewer        UserRole = "viewer"
	UserRoleContributor   UserRole = "contributor"
	UserRoleEditor        UserRole = "editor"
	UserRoleAdministrator UserRole = "administrator"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VerificationStatus string

const (
	VerificationStatusVerified  VerificationStatus = "verified"
	VerificationStatusCommunity VerificationStatus = "community"
	VerificationStatusPending   VerificationStatus = "pending"
)

func (e *VerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationStatus(s)
	case string:
		*e = VerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationStatus: %T", src)
	}
	return nil
}

type NullVerificationStatus struct {
	VerificationStatus VerificationStatus `json:"verification_status"`
	Valid              bool               `json:"valid"` // Valid is true if VerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationStatus), nil
}

type VisibilityStatus string

const (
	VisibilityStatusDraft        VisibilityStatus = "draft"
	VisibilityStatusPublished    VisibilityStatus = "published"
	VisibilityStatusArchived     VisibilityStatus = "archived"
	VisibilityStatusReview       VisibilityStatus = "review"
	VisibilityStatusNeedsChanges VisibilityStatus = "needs_changes"
)

func (e *VisibilityStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisibilityStatus(s)
	case string:
		*e = VisibilityStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VisibilityStatus: %T", src)
	}
	return nil
}

type NullVisibilityStatus struct {
	VisibilityStatus VisibilityStatus `json:"visibility_status"`
	Valid            bool             `json:"valid"` // Valid is true if VisibilityStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisibilityStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VisibilityStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisibilityStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisibilityStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisibilityStatus), nil
}

type Alias struct {
	ID       uuid.UUID `json:"id"`
	AppID    uuid.UUID `json:"app_id"`
	Alias    string    `json:"alias"`
	Priority int32     `json:"priority"`
}

type App struct {
	ID                 uuid.UUID          `json:"id"`
	Slug               string             `json:"slug"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	OrganizationID     uuid.UUID          `json:"organization_id"`
	VisibilityStatus   VisibilityStatus   `json:"visibility_status"`
	HealthStatus       HealthStatus       `json:"health_status"`
	VerificationStatus VerificationStatus `json:"verification_status"`
	RankingWeight      int32              `json:"ranking_weight"`
	IconKey            string             `json:"icon_key"`
	Metadata           []byte             `json:"metadata"`
	Version            int64              `json:"version"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	Source             string             `json:"source"`
	SourceAppID        pgtype.UUID        `json:"source_app_id"`
	UpdatedBy          pgtype.UUID        `json:"updated_by"`
}

type AppCategory struct {
	AppID      uuid.UUID `json:"app_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

type AppLink struct {
	ID       uuid.UUID `json:"id"`
	AppID    uuid.UUID `json:"app_id"`
	LinkType string    `json:"link_type"`
	Url      string    `json:"url"`
}

type AppPlatform struct {
	AppID      uuid.UUID `json:"app_id"`
	PlatformID uuid.UUID `json:"platform_id"`
}

type AppPricing struct {
	AppID     uuid.UUID `json:"app_id"`
	PricingID uuid.UUID `json:"pricing_id"`
}

type AppRelease struct {
	ID           uuid.UUID `json:"id"`
	AppID        uuid.UUID `json:"app_id"`
	Version      string    `json:"version"`
	ReleaseDate  time.Time `json:"release_date"`
	ReleaseNotes string    `json:"release_notes"`
}

type AppTag struct {
	AppID uuid.UUID `json:"app_id"`
	TagID uuid.UUID `json:"tag_id"`
}

type AuditLog struct {
	ID           uuid.UUID          `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   *string            `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	Ip           *string            `json:"ip"`
	UserAgent    *string            `json:"user_agent"`
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
}

type Category struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

type Import struct {
	ID         uuid.UUID          `json:"id"`
	StartedAt  time.Time          `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Source     string             `json:"source"`
	Status     string             `json:"status"`
	Report     []byte             `json:"report"`
}

type Medium struct {
	ID         uuid.UUID `json:"id"`
	AppID      uuid.UUID `json:"app_id"`
	MediaType  string    `json:"media_type"`
	MediaKey   string    `json:"media_key"`
	OrderIndex int32     `json:"order_index"`
}

type Organization struct {
	ID         uuid.UUID          `json:"id"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	WebsiteUrl string             `json:"website_url"`
	CreatedAt  time.Time          `json:"created_at"`
	UpdatedAt  time.Time          `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `json:"id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	EventVersion  int32              `json:"event_version"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Attempts      int32              `json:"attempts"`
	LastError     *string            `json:"last_error"`
	NextAttemptAt time.Time          `json:"next_attempt_at"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      *string            `json:"locked_by"`
}

type PasswordReset struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	HashedToken string             `json:"hashed_token"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Platform struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

type Pricing struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

type Session struct {
	ID         string             `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Ip         *string            `json:"ip"`
	UserAgent  *string            `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type Tag struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
