// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveShadowDrafts(ctx context.Context, sourceAppID pgtype.UUID) error
	ClaimEvents(ctx context.Context, arg ClaimEventsParams) ([]OutboxEvent, error)
	CloneAppAsShadowDraft(ctx context.Context, arg CloneAppAsShadowDraftParams) (App, error)
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	CreateAppAlias(ctx context.Context, arg CreateAppAliasParams) error
	CreateAppCategory(ctx context.Context, arg CreateAppCategoryParams) error
	CreateAppLink(ctx context.Context, arg CreateAppLinkParams) error
	CreateAppMedia(ctx context.Context, arg CreateAppMediaParams) error
	CreateAppPlatform(ctx context.Context, arg CreateAppPlatformParams) error
	CreateAppPricing(ctx context.Context, arg CreateAppPricingParams) error
	CreateImport(ctx context.Context, arg CreateImportParams) (Import, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	CreatePlatform(ctx context.Context, arg CreatePlatformParams) (Platform, error)
	DeleteAppAliases(ctx context.Context, appID uuid.UUID) error
	DeleteAppCategories(ctx context.Context, appID uuid.UUID) error
	DeleteAppLinks(ctx context.Context, appID uuid.UUID) error
	DeleteAppMedia(ctx context.Context, appID uuid.UUID) error
	DeleteAppPlatforms(ctx context.Context, appID uuid.UUID) error
	DeleteAppPricing(ctx context.Context, appID uuid.UUID) error
	GetAdminDashboardStats(ctx context.Context) (GetAdminDashboardStatsRow, error)
	GetApp(ctx context.Context, id uuid.UUID) (App, error)
	GetAppBySlug(ctx context.Context, slug string) (App, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetPlatformBySlug(ctx context.Context, slug string) (Platform, error)
	GetPricingBySlug(ctx context.Context, slug string) (Pricing, error)
	GetReviewQueue(ctx context.Context) ([]App, error)
	GetTagBySlug(ctx context.Context, slug string) (Tag, error)
	GetWorkerHealth(ctx context.Context) (GetWorkerHealthRow, error)
	LinkAppPlatform(ctx context.Context, arg LinkAppPlatformParams) error
	MarkEventCompleted(ctx context.Context, id uuid.UUID) error
	MarkEventDead(ctx context.Context, arg MarkEventDeadParams) error
	MarkEventFailed(ctx context.Context, arg MarkEventFailedParams) error
	PatchApp(ctx context.Context, arg PatchAppParams) (App, error)
	ReclaimStaleLocks(ctx context.Context, attempts int32) error
	UpdateApp(ctx context.Context, arg UpdateAppParams) (App, error)
	UpdateAppStatus(ctx context.Context, arg UpdateAppStatusParams) (App, error)
	UpdateImport(ctx context.Context, arg UpdateImportParams) (Import, error)
}

var _ Querier = (*Queries)(nil)
