// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: taxonomies.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createPlatform = `-- name: CreatePlatform :one
INSERT INTO platforms (id, slug, name) VALUES ($1, $2, $3) RETURNING id, slug, name
`

type CreatePlatformParams struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

func (q *Queries) CreatePlatform(ctx context.Context, arg CreatePlatformParams) (Platform, error) {
	row := q.db.QueryRow(ctx, createPlatform, arg.ID, arg.Slug, arg.Name)
	var i Platform
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, slug, name FROM categories WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const getPlatformBySlug = `-- name: GetPlatformBySlug :one
SELECT id, slug, name FROM platforms WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetPlatformBySlug(ctx context.Context, slug string) (Platform, error) {
	row := q.db.QueryRow(ctx, getPlatformBySlug, slug)
	var i Platform
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const getPricingBySlug = `-- name: GetPricingBySlug :one
SELECT id, slug, name FROM pricing WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetPricingBySlug(ctx context.Context, slug string) (Pricing, error) {
	row := q.db.QueryRow(ctx, getPricingBySlug, slug)
	var i Pricing
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, slug, name FROM tags WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const linkAppPlatform = `-- name: LinkAppPlatform :exec
INSERT INTO app_platforms (app_id, platform_id) VALUES ($1, $2)
`

type LinkAppPlatformParams struct {
	AppID      uuid.UUID `json:"app_id"`
	PlatformID uuid.UUID `json:"platform_id"`
}

func (q *Queries) LinkAppPlatform(ctx context.Context, arg LinkAppPlatformParams) error {
	_, err := q.db.Exec(ctx, linkAppPlatform, arg.AppID, arg.PlatformID)
	return err
}
