// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimEvents = `-- name: ClaimEvents :many
UPDATE outbox_events 
SET status = 'processing', 
    locked_at = NOW(), 
    locked_by = $1 
WHERE id IN (
    SELECT id FROM outbox_events 
    WHERE status = 'pending' 
      AND next_attempt_at <= NOW() 
    ORDER BY created_at ASC 
    LIMIT $2 
    FOR UPDATE SKIP LOCKED
)
RETURNING id, event_type, payload, status, created_at, event_version, aggregate_id, attempts, last_error, next_attempt_at, locked_at, locked_by
`

type ClaimEventsParams struct {
	LockedBy *string `json:"locked_by"`
	Limit    int32   `json:"limit"`
}

func (q *Queries) ClaimEvents(ctx context.Context, arg ClaimEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimEvents, arg.LockedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.EventVersion,
			&i.AggregateID,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.LockedAt,
			&i.LockedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkerHealth = `-- name: GetWorkerHealth :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'pending') AS pending_events,
    COUNT(*) FILTER (WHERE status = 'dead') AS dead_events,
    COALESCE(MIN(created_at) FILTER (WHERE status = 'pending'), NOW()) AS oldest_pending,
    MAX(updated_at) FILTER (WHERE status = 'completed') AS last_successful
FROM outbox_events
`

type GetWorkerHealthRow struct {
	PendingEvents  int64       `json:"pending_events"`
	DeadEvents     int64       `json:"dead_events"`
	OldestPending  interface{} `json:"oldest_pending"`
	LastSuccessful interface{} `json:"last_successful"`
}

func (q *Queries) GetWorkerHealth(ctx context.Context) (GetWorkerHealthRow, error) {
	row := q.db.QueryRow(ctx, getWorkerHealth)
	var i GetWorkerHealthRow
	err := row.Scan(
		&i.PendingEvents,
		&i.DeadEvents,
		&i.OldestPending,
		&i.LastSuccessful,
	)
	return i, err
}

const markEventCompleted = `-- name: MarkEventCompleted :exec
UPDATE outbox_events 
SET status = 'completed', 
    updated_at = NOW() 
WHERE id = $1
`

func (q *Queries) MarkEventCompleted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventCompleted, id)
	return err
}

const markEventDead = `-- name: MarkEventDead :exec
UPDATE outbox_events 
SET status = 'dead', 
    attempts = attempts + 1, 
    last_error = $2, 
    locked_at = NULL, 
    locked_by = NULL,
    updated_at = NOW()
WHERE id = $1
`

type MarkEventDeadParams struct {
	ID        uuid.UUID `json:"id"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) MarkEventDead(ctx context.Context, arg MarkEventDeadParams) error {
	_, err := q.db.Exec(ctx, markEventDead, arg.ID, arg.LastError)
	return err
}

const markEventFailed = `-- name: MarkEventFailed :exec
UPDATE outbox_events 
SET status = 'pending', 
    attempts = attempts + 1, 
    last_error = $2, 
    next_attempt_at = $3, 
    locked_at = NULL, 
    locked_by = NULL,
    updated_at = NOW()
WHERE id = $1
`

type MarkEventFailedParams struct {
	ID            uuid.UUID `json:"id"`
	LastError     *string   `json:"last_error"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

func (q *Queries) MarkEventFailed(ctx context.Context, arg MarkEventFailedParams) error {
	_, err := q.db.Exec(ctx, markEventFailed, arg.ID, arg.LastError, arg.NextAttemptAt)
	return err
}

const reclaimStaleLocks = `-- name: ReclaimStaleLocks :exec
UPDATE outbox_events 
SET status = 'pending', 
    locked_at = NULL, 
    locked_by = NULL,
    updated_at = NOW()
WHERE status = 'processing' 
  AND locked_at < NOW() - INTERVAL '5 MINUTES'
  AND attempts < $1
`

func (q *Queries) ReclaimStaleLocks(ctx context.Context, attempts int32) error {
	_, err := q.db.Exec(ctx, reclaimStaleLocks, attempts)
	return err
}
